### PR TITLE
add support for optional custom command and replace_string parameter of vcs_tag

### PR DESCRIPTION
**Pull request by axxel**
The test 73 executes as before but I changed it nonetheless by adding another test-case for the new custom command feature.

I also changed the default behavior as discussed before ('hg id -n' and 'git describe --dirty=+'). This makes the git and hg backends behave consistent and in a way @stoggy and I have a use for it. In case you have a reason to change that to something else, it is a trivial change.

I used your dictionary traversal approach for detecting the vcs system but moved it into interpreter.py for config-time detection and logging. The code is tested for git, hg and svn as well as custom commands and a forced fallback case.

Possible future extension (not implemented):
 * The use of the internal regex_selector to cope with the svn situation is a general approach that could trivially be made usable for the meson user in case you should later change your mind with regard to extending the vcs_tag interface even further for custom svn based commands.
 * The use of the vcs-internal dependencies, which would allow the user to optionally set build_always to false and get a truly no-op ninja build if he does not care for an up to date 'dirty' flag.
 * Adding support for yet another vcs system should hopefully be a one-liner, now.

### CODE REVIEW

**Comment by jpakkane** [comment]
Looking really nice, thanks. There are just two minor things.

First the test file is misspelt (vcstag-cusom.c instead of vcstag-custom.c).

Secondly, please move the detector function from interpreter.py to mesonlib.py.

**Comment by axxel** [comment]
I'll change that (soonish). Glad, we could find something acceptable for everyone.
P.S. I just wasted another 8 hours fighting with cmake's BundleUtilities and my new qt5 setup :-(. If only everything would "just work"....

**Comment by axxel** [comment]
done. (not sure whether github automatically notified you about the two new commits, I'm not a regular github user)

**Comment by jpakkane** [comment]
It does not send notifications, apparently. No matter, looking fine now so merging. Thanks.

**Pull request merged**
