### PR TITLE
tests: include time of test execution

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@jpakkane much better view: http://vm666.clanwars.org/job/meson-request/16/testReport/%28root%29/

btw, what happened with your credentials? 
```
Could not update commit status of the Pull Request on GitHub.
java.io.IOException: {"message":"Bad credentials"
```

**Comment by jpakkane** [comment]
I regenerated the token and reset the settings. I still get errors when trying to create access token in Jenkins, though.

**Comment by ignatenkobrain** [comment]
@jpakkane on start of test it was OK with credentials, it set status to `Waiting to hear about 9e13446`, but on en

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by ignatenkobrain** [comment]
@jpakkane now it doesn't work (credentials), how did you set it 30 mins ago? when all worked

**Comment by jpakkane** [comment]
I hadn't touched it at all back then. It just started working by itself.

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by ignatenkobrain** [comment]
@jpakkane where we can have live chat? probably IRC channel to not flood in github issue.

**Comment by jpakkane** [comment]
Let's do #mesonbuild at freenode.

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by ignatenkobrain** [comment]
retest this please

**Pull request closed without merging**
