### PR TITLE
modules/gnome: make program name as optional argument. Closes #76

### LINKED ISSUE #76: modules/gnome: g-ir-scanner should have 'prog' optional
```
       --program-arg=ARG
              Additional argument to pass to program for introspection.
```

and we want to make it as kwarg and it should be optional

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Closes #76

### CODE REVIEW

**Comment by jpakkane** [comment]
Seems reasonable, but since we are doing this, we might as well add shared library introspection at the same time. That should correspond to -i and -L flags to g-ir-scanner, right?

**Comment by ignatenkobrain** [comment]
Probably this is true, but I have no test cases for this. (This issue/case got by porting one big lib to meson)

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by jpakkane** [comment]
Good stuff. Thanks.

**Pull request merged**
