### PR TITLE
modules/gnome: auto-set gobject-introspection directories and install gir

### PR DESCRIPTION
**Pull request by ignatenkobrain**
Signed-off-by: Igor Gnatenko <i.gnatenko.brain@gmail.com>

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by ignatenkobrain** [comment]
retest this please

**Comment by ignatenkobrain** [comment]
@jpakkane what do you think?

**Comment by jpakkane** [comment]
Looks fine.

**Pull request merged**
