### PR TITLE
add RPM module (Closes #49)

### LINKED ISSUE #49: [RFC] create RPM packages from meson
I think I can implement subj, but I need to know is it needed, what we're expecting from this. Some thoughts:

* we can aggregate all `dependency()` and add to `.spec` file via `BuildRequires: pkgconfig(XXX)`
* we can use `vcs_tag()` to get version-release
* we can use `project()` to get `Name:`

I think this would be useful to allow developers properly package RPM or DEB or something.

Probably I can add just new rpm module and add `generate_spec()` function which will create new spec with needed info.

What do you think?

### PR DESCRIPTION
**Pull request by ignatenkobrain**
It's basic implementation of things which I described in #49

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@jpakkane what do you think?

**Comment by jpakkane** [comment]
Looks pretty nice. There are few niggles, though.

- the spec file is generated into the dir where Meson was invoked from, it should go in the build directory
- the function <tt>generate_spec</tt> should be called <tt>generate_spec_template</tt> to make it clear it may need hand editing
- some projects have a directory called build already, it should be something more unique such as rpmbuilddir
- presumably RPM passes the compiler flags to use with CFLAGS et al? If yes, then the Meson command should have --buildtype=plain, if no it should have --buildtype=debugoptimized
- trunk changed in the mean time to get a subdirectory 4, change the number in this one to 5
- this spec file does not run tests, it should call 'ninja-build test' at some point

**Comment by ignatenkobrain** [comment]
- [X] the spec file is generated into the dir where Meson was invoked from, it should go in the build directory
- [X] the function generate_spec should be called generate_spec_template to make it clear it may need hand editing

**Comment by ignatenkobrain** [comment]
- [X] some projects have a directory called build already, it should be something more unique such as rpmbuilddir
- [X] presumably RPM passes the compiler flags to use with CFLAGS et al? If yes, then the Meson command should have --buildtype=plain, if no it should have --buildtype=debugoptimized
- [] trunk changed in the mean time to get a subdirectory 4, change the number in this one to 5
don't understand this.
- [X] this spec file does not run tests, it should call 'ninja-build test' at some point

**Comment by ignatenkobrain** [comment]
> trunk changed in the mean time to get a subdirectory 4, change the number in this one to 5
don't understand this.

**Comment by ignatenkobrain** [comment]
@jpakkane I've also added support for auto-generating build requires for non-default compilers (fortran, vala, objc, objc++)

**Comment by jpakkane** [comment]
What I meant is that you should rename your directory from "4 rpm" to "5 rpm".

**Comment by ignatenkobrain** [comment]
@jpakkane done

**Comment by jpakkane** [comment]
Thanks for fixing. One last question. What is the configure file you generate for? If it is needed by the rpm machinery please print a comment in the resulting rpm template explaining why it needs to be there.

**Comment by ignatenkobrain** [comment]
@jpakkane, it's because only way to apply ALL compiler/linker flags (CFLAGS, CXXFLAGS, FFLAGS, FCFLAGS, LDFLAGS) is using `%configure` macros from RPM.

On my system it is:
```
$ rpm --eval %configure 

  CFLAGS="${CFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CFLAGS ; 
  CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CXXFLAGS ; 
  FFLAGS="${FFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FFLAGS ; 
  FCFLAGS="${FCFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FCFLAGS ; 
  LDFLAGS="${LDFLAGS:--Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld}"; export LDFLAGS; 
  [ "1" = 1 ] && for i in $(find . -name config.guess -o -name config.sub) ; do 
      [ -f /usr/lib/rpm/redhat/$(basename $i) ] && /usr/bin/rm -f $i && /usr/bin/cp -fv /usr/lib/rpm/redhat/$(basename $i) $i ; 
  done ; 
  [ "1" = 1 ] && [ x != "x-specs=/usr/lib/rpm/redhat/redhat-hardened-ld" ] && 
      for i in $(find . -name ltmain.sh) ; do 
        /usr/bin/sed -i.backup -e 's~compiler_flags=$~compiler_flags="-specs=/usr/lib/rpm/redhat/redhat-hardened-ld"~' $i 
      done ; 
  ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu \
	--program-prefix= \
	--disable-dependency-tracking \
	--prefix=/usr \
	--exec-prefix=/usr \
	--bindir=/usr/bin \
	--sbindir=/usr/sbin \
	--sysconfdir=/etc \
	--datadir=/usr/share \
	--includedir=/usr/include \
	--libdir=/usr/lib64 \
	--libexecdir=/usr/libexec \
	--localstatedir=/var \
	--sharedstatedir=/var/lib \
	--mandir=/usr/share/man \
	--infodir=/usr/share/info
```

and if we want to use proper flags we need to execute that macros, but it's executing `./configure` and in our case we should use blank executable file (for example, one package in Fedora: http://pkgs.fedoraproject.org/cgit/gmqcc.git/tree/gmqcc.spec#n37)

**Comment by ignatenkobrain** [comment]
@jpakkane now I think it's ready for merge.

**Comment by jpakkane** [comment]
I looked through RPM docs and it seems that the flags in question will be set in the RPM_OPT_FLAGS environment variable. We should also set the install prefix when configuring Meson (default is /usr/local, which is wrong for package bulding).

Combining these two, it would seem that the way to do this is to not have the configure bits but instead set up Meson with this:

    CFLAGS="${RPM_OPT_FLAGS}" meson .. --prefix=%{_prefix} --buildtype=plain

Does this seem correct to you?

**Comment by jpakkane** [comment]
That still leaves out global ldflags. And the documentation I can found does not say where RPM sets those up...

**Comment by jpakkane** [comment]
This is weird. On my fedora test machine, rpm --eval %configure or %cmake does not set ldflags at all. However if it did, then the (hopefully final) correct stanza would be this:

CPPFLAGS="%{__global_cflags}" LDFLAGS="%{__global_ldflags}" meson .. --prefix=%{prefix} --buildtype=plain

**Comment by ignatenkobrain** [comment]
@jpakkane done.

**Comment by ignatenkobrain** [comment]
@jpakkane done with properly solution from RPM side (added `%meson` macros. See #55)

Any issues?

**Comment by ignatenkobrain** [comment]
@jpakkane Probably there should be a bit more better thing to detect install or not-install RPM macros, but I don't know. If no other issues - please merge with commit with fix of choosing install or not install rpm macros.

**Comment by jpakkane** [comment]
Looks fine. Let's get this in now.

**Comment by bauer-at-work** [comment]
Just to link back the info here: The meson rpm module has since been removed.  
See: https://github.com/mesonbuild/meson/issues/9764

**Comment by dcbaker** [comment]
I'll add, the rational for removing it was that the RPM module used a configured Meson build to generate an RPM spec file. With the existence of the introspection API, the hope was that a standalone script could be created that read the introspection data and dumped out a spec file without the need to doing any real configuration.

**Pull request merged**
