### PR TITLE
use sphinx as documentation system + added porting from autotools doc

### PR DESCRIPTION
**Pull request by ignatenkobrain**
compile docs with `sphinx-build-3 -b html source/ .`

This allow us to have contributors to documentation, because they can write patch and propose pull request.

I don't have access to sources of current docs, so I can't convert existing documentation.

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Doesn't Sphinx come with a makefile for building?

**Comment by ignatenkobrain** [comment]
We can add make file, but I dropped it because more easy to use
sphinx-build directly.

-Igor Gnatenko

**Comment by kirbyfan64** [comment]
@ignatenkobrain Not necessarily. `make html` is shorter than `sphinx-build-3 -b html source/ .`.

Sphinx even will generate a batch script used the same way.

**Comment by jpakkane** [comment]
The biggest downside of Sphinx is that it breaks Github's web editor which is what I use most of the time. It also breaks all existing outside links to current wiki pages. There's also the thing that just changing the source is not enough, you need to remember to generate the pages and commit them in.

The main point of this MR was that it allows people to send MRs to the wiki. It turns out that you can do that already. The downside is that you need to send them as old-fashioned patches. Thus let's stick with Github infrastructure.

**Pull request closed without merging**
