### PR TITLE
tests: refactor to using nose framework

### PR DESCRIPTION
**Pull request by ignatenkobrain**
If we're using python-unittest we don't need to handle test results manually (counting and etc).

As a plus junit switch added there to easy control test results in jenkins.

Some examples of new test system:
* http://vm666.clanwars.org/job/meson-brain/7/console
* http://vm666.clanwars.org/job/meson-brain/lastCompletedBuild/testReport/
* http://vm666.clanwars.org/job/meson-brain/lastCompletedBuild/testReport/%28root%29/TestsContainer/history/
* http://vm666.clanwars.org/job/meson-brain/lastCompletedBuild/testReport/%28root%29/TestsContainer/

### CODE REVIEW

**Comment by ignatenkobrain** [comment]
@jpakkane what do you think? I'd very want to get junit tables in jenkins to more better look at tests ;)

**Comment by jpakkane** [comment]
Overall seems nice but some issues crop up.

First of all the system has changed to ASCII sorting instead of numerical sorting. This means that it first runs test 1, then 10, 11, 12 and so on until 19, 2, 20 etc. gather_tests goes through a fair bit of effort to sort everything properly, we should preserve that. And no, renaming directories to have leading zeros is *not* an acceptable solution. Similarly the test log should start with the basic tests and go on to more specialised ones. Currently "common" gets sorted first but if we ever add, say, Ada support then this is no longer the case.

Another thing is that the linked pages do not show stdout and stderr for those tests, they are always empty. It would be nice to get the output there as well.

**Comment by ignatenkobrain** [comment]
@jpakkane hm, I will try to fix part with sorting.

But I don't have ideas how to fix showing stdout/stderr in linked page, but I hope you can try to fix this.

**Comment by jpakkane** [comment]
The simplest solution would seem to be to change the dict used to store the tests into an array.

**Comment by ignatenkobrain** [comment]
@jpakkane I didn't write python-unittest library, but AFAIK it's sorting tests itself. As added in class.

**Comment by ignatenkobrain** [comment]
@jpakkane 
`Note that the order in which the various test cases will be run is determined by sorting the test function names with respect to the built-in ordering for strings.` @ https://docs.python.org/2/library/unittest.html

**Comment by jpakkane** [comment]
Gaaah! Fail!

Looking at the specification of junit xml, it might be simplest to just generate the xml by hand. Its format is really simple. Can you just write it to a named file and tell Jenkins to pick it up from there?

**Comment by ignatenkobrain** [comment]
Give me 1 day to make this. I'm working on it.

-Igor Gnatenko

**Comment by jpakkane** [comment]
No rush. I would imagine the simplest solution would be to take current trunk and just print the xml file with elementtree alongside the existing text based file. There's no harm in producing it always.

**Comment by ignatenkobrain** [comment]
@jpakkane I've switched to use python3-nose which can generate JUnit files without external modules, it's not sorting tests and proceed stdout/stderr properly to xml. See examples with new commit:

* http://vm666.clanwars.org/job/meson-brain/13/console
* http://vm666.clanwars.org/job/meson-brain/13/testReport/junit/%28root%29/test/test_cases_common_1_trivial/

**Comment by jpakkane** [comment]
I went through the unit test code I came to the conclusion that the way I had written is was crappy. Refactored it to look sane. As a side effect I put in junit xml reporting (writes to <tt>meson-test-run.xml</tt>. Can you test if that works with Jenkins?

**Comment by ignatenkobrain** [comment]
@jpakkane no, it doesn't work and making xml by hand is very bad idea. why do not use nosetests? I've also planned to write more tests.

```python
Traceback (most recent call last):
  File "./run_tests.py", line 316, in <module>
    run_tests()
  File "./run_tests.py", line 239, in run_tests
    all_tests = detect_tests_to_run()
  File "./run_tests.py", line 215, in detect_tests_to_run
    all_tests.append(('java'), [])
TypeError: append() takes exactly one argument (2 given)
```

**Comment by jpakkane** [comment]
Fixed that.

The reason not to use nose is that we want to work on as many platforms as possible. This includes especially Windows. On those platforms having external dependencies is a world of pain. Thus we should stick only to Python standard library unless it is absolutely necessary. I updated the development documentation with this info just now as I noticed I had forgotten to write this down. Sorry about that.

**Comment by ignatenkobrain** [comment]
@jpakkane as you can see, it doesn't work OK. http://vm666.clanwars.org/job/meson/lastCompletedBuild/testReport/%28root%29/dummy/

**Comment by ignatenkobrain** [comment]
@jpakkane take a look for #79.

**Pull request closed without merging**
